### ISSUE TITLE
Can ng-mockito be used for spying on a service / component?

### ISSUE THREAD

**Issue by pauleustice** [qupaya/ng-mockito#39]
Hi! I recently discovered that ts-mockito no longer seems to work with Angular 14 in our Jest tests, so am investigating solutions and/or workarounds.

Does ng-mockito provide spying (and partial mocking) on a service (or component) under test, in the way that ts-mockito does?

For example:

// some.service.spec.ts

```typescript
describe('SomeService', () => {
  let someServiceSpy: SomeService;
  
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        SomeService, // <------ The service we are testing
      ],
    });

    service = TestBed.inject(SomeService);
    someServiceSpy = spy(service);
    
    // ---------- Used to mock return values
    when(someServiceSpy.someMethod(anything())).thenReturn('foo');
  });
  
  it('should spy on SomeService methods', () => {
    service.aMethodThatCallsSomeMethod({ some: 'value' });
  
    verify(
      // ---------- Used to spy on arguments and calls
      someServiceSpy.someMethod(
        deepEqual({
          some: 'value',
        }),
      ),
    ).once();
  });
});
```

Thanks!

**Comment by distante** [comment]
`ng-mockito` uses `ts-mockito` in the background. The main difference is that `ns-mockito` parses the metadata and creates the correct provide object.

BTW, at qupaya we are using both `ts-mockito` and `ng-mockito` with angular 14

For your question, yes it can see the readme: https://github.com/qupaya/ng-mockito/blob/main/libs/ng-mockito/ng-mockito/README.md#stubbing-inline-or-pre-setup

**Comment by pauleustice** [comment]
@distante Thanks, that's really interesting that you have ts-mockito working with ng14. Are you using Jest or Karma? Not sure if it matters, but we're using Jest, and observable class fields on services seem to get stubbed when I run `spy(someService)` even though I'm not explicitly overriding them with `when(someService.theObservable$)`.

I added some logs to the ts-mockito code and the output differs between ng 12 and ng14 🤷

**Comment by distante** [comment]
We are using jest, but to be honest, we never use ts-mockito `spy` (at least I think I never see it on own code base)

**Comment by pauleustice** [comment]
Ah ok - My next step is to test out a simple use-case in a fresh repo but I'm pretty sure spy has an issue with ng14 based on what I'm seeing. It'll be a huge migration, but I really like the look of ng-mockito so we'll look to move to your library as a long-term goal anyhow, especially since ts-mockito is no longer maintained.

**Comment by pauleustice** [comment]
@distante FYI, I have isolated the problem in my test repo to it being a Typescript issue, not Angular 14 (they were upgraded at the same time). Anything from TS 4.4.2 onwards will break the following conditions:

- Testing a service that has an Observable
  - if the Observable uses `combineLatest` from RxJS (probably other operators, but I haven't tested those)
  - if you use ts-mockito's `spy(service)`

There's no issue if the Observable is just something like:

```
  observable$ = new BehaviorSubject('someValue');
```

Just informing you in case this causes issues for your library, since you build on top of ts-mockito. If you have any idea why that might be it would help alot. For now I'm going to investigate the change log between 3.5.2 and 4.4.2

**Comment by Markus-Ende** [comment]
Thanks for clarifying! Closing this, as it is not connected to ng-mockito.
